services:
  web:
    build: .
    container_name: reactjs
    ports:
      - "3000:3000"
    volumes:
    - .:/app
    - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: true
    stdin_open: true
    tty: true
    command: npm start

volumes:
  app: